dataset_name: DeepFakeDetection
input_json: preprocessing/rearrangements/dataset_json_mtcnn/DeepFakeDetection.json

output_base_dir: clip/embeddings/benchmarks/layer16_dfd

model:
  name: ViT-L-14-336-quickgelu
  pretrained: openai

extract:
  blocks: [16]
  include_final: false

T: 96
batch_size: null
seed: 1024

device: cuda
max_videos: null
