dataset_name: WildDeepfakes
input_json: preprocessing/rearrangements/dataset_json_mtcnn/WildDeepfakes.json

output_base_dir: clip/embeddings/benchmarks/wilddf_layer16

model:
  name: ViT-L-14-336-quickgelu
  pretrained: openai

extract:
  blocks: [16]
  include_final: false

T: 48
batch_size: null
seed: 1024

device: cuda
max_videos: null
